### ISSUE TITLE
infinity/NaN values in prediction

### ISSUE THREAD

**Issue by yitang** [aksnzhy/xlearn#10]
I built 5 model using a subset of the full training datasets, and then predict on the test dataset. as you see, I got infinity/NaN values. what could possibly be the reason? 

I could provide all the data if needed.

Thanks, 

Yi
![screenshot from 2017-11-26 11-33-23](https://user-images.githubusercontent.com/6054101/33239622-a2196076-d29d-11e7-95ee-b210df669e0e.png)

![screenshot from 2017-11-26 11-34-03](https://user-images.githubusercontent.com/6054101/33239626-ba7448e8-d29d-11e7-9348-db5e5dc7d509.png)

**Comment by aksnzhy** [comment]
Hi can you share your data to me. My email ismctt90@gmail.com

**Comment by yitang** [comment]
sure. it will be in your inbox shortly.

**Comment by yitang** [comment]
Okay, I've sent you the data.

what i did:

for i in 0..5:
1. build model on tr_f{i}, using va_f{i} as validation dataset,
2. run prediction on test.ffm.txt

i repeat modelling/prediction using randomly sampled parameters. sometimes i don't have NAs, and form times i do.

one thing is that i didn't see any NAs in predicting validation datasets.. could it be data format issues?

**Comment by aksnzhy** [comment]
The problem comes from your csv data ，you need to use a dummy placeholder in the last of you test data in every line, this is because the xlearn will automatically treat the last data as y when using csv. I am very sorry for the csv problem.

**Comment by aksnzhy** [comment]
You do not need to do this when using Libsvm and libffm .

**Comment by yitang** [comment]
Sry but I didn't use CSV. The dataset I email you are in Libffm format, did I send you wrong one? 

And in the test dataset I send you, I have a dummy placeholder of target in the first field. Is it correct?
