### ISSUE TITLE
How to set the epoch number?

### ISSUE THREAD

**Issue by yushuai** [aksnzhy/xlearn#11]
param = { 'task':'reg',
          'lr' : 1e-1,
          #'lambda' : 0.002,
           'epoch':100,
          'metric' : 'rmse' }
I just want to set the epoch number to 100, then the program output a error:
 _check_call(_LIB(XLearnSetInt(ctypes.byref(self.handle), 
NameError: global name 'XLearnSetInt' is not defined

**Comment by aksnzhy** [comment]
Hi, we have already fixed this problem and you can try it now.
Thanks for your issue!
