### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mrgloom** [aksnzhy/xlearn#12]
How to install? Is there something like `sudo pip install xlearn`?

**Comment by KhaledTo** [comment]
This might be useful: https://github.com/aksnzhy/xlearn/blob/master/doc/install.md

**Comment by aksnzhy** [comment]
You can build xlearn by using cmake. Please see the details in installation page.

**Comment by weiweijiuzaizhe** [comment]
I found there is something wrong in multi-thread compling.
If you use command:
make -j4 
sometimes you will meet the error:

```
[ 34%] Building CXX object src/loss/CMakeFiles/loss.dir/cross_entropy_loss.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 4
make[1]: *** [gtest/CMakeFiles/gtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Linking CXX shared library libscore.so
[ 36%] Building CXX object src/loss/CMakeFiles/loss.dir/metric.cc.o
```

If you use command:
make
the compile task will always success.

**Comment by aksnzhy** [comment]
Thanks for your issue !
But I have never meet this problem and it seems that this error comes from the compiler, not xLearn.
Can you share your compiler and OS   information ?

**Comment by weiweijiuzaizhe** [comment]
my  compiler and OS information
```
[root@****:/root 2017-11-28 17:23:38]#cat /proc/version
Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017
[root@****:/root 2017-11-28 17:25:47]#make -v 
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by HyperGroups** [comment]
problem with install the python-interface
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "xlearn/libpath.py", line 45, in find_lib_path
    'Cannot find xlearn Library in the candidate path'
__builtin__.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

**Comment by mrgloom** [comment]
I have build it with gcc 4.9 with no problem.

Also I found that it have setup.py under `xlearn/build/python-package` and installed it this way:
https://stackoverflow.com/questions/1471994/what-is-setup-py

**Comment by aksnzhy** [comment]
Did you build your libxlearn library successfully? You can check it in xleanr/lib/

**Comment by AvashDahal** [comment]
> I have build it with gcc 4.9 with no problem.
> 
> Also I found that it have setup.py under `xlearn/build/python-package` and installed it this way: https://stackoverflow.com/questions/1471994/what-is-setup-py
> 
> And after adding to `~/.bashrc` `export PYTHONPATH=/home/user/deep_learning/data3/xlearn/python-package/xlearn` I get error on import:
> 
> ```
> Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 30 2017, 18:42:57) 
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import xlearn as xl
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/deep_learning/data3/xlearn/python-package/xlearn/xlearn.py", line 5, in <module>
>     from base import _LIB, XLearnHandle
>   File "/home/user/deep_learning/data3/xlearn/python-package/xlearn/base.py", line 20, in <module>
>     _LIB = _load_lib()
>   File "/home/user/deep_learning/data3/xlearn/python-package/xlearn/base.py", line 13, in _load_lib
>     lib_path = find_lib_path()
>   File "/home/user/deep_learning/data3/xlearn/python-package/xlearn/libpath.py", line 45, in find_lib_path
>     'Cannot find xlearn Library in the candidate path'
> libpath.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path
> ```

HELLOO PLEASE HELP I AM GETTING tHIS SAME ERROOORRR
