### ISSUE TITLE
 训练速度太慢

### ISSUE THREAD

**Issue by drfilter** [aksnzhy/xlearn#126]
你好，我的训练集26G,  测试集2.9G
param = {'task':'binary', 'lr':0.2, 'lambda':0.002, 'metric': 'auc', 'nthread': 20, 'k': 8, 'epoch':20, 'opt': 'ftrl'}
使用服务器，32核，cpu: 2399.906 Mhz
使用0.31 版本:
[------------] Number of Feature: 84994
[------------] Number of Field: 31
[------------] Time cost for reading problem: 180.55 (sec)
[ ACTION     ] Initialize model ...
[------------] Model size: 242.20 MB
[------------] Time cost for model initial: 0.44 (sec)
一轮需要 5206.04 秒

**Comment by aksnzhy** [comment]
请用命令行版本试试，python 版本在多核下可能会比较慢。

**Comment by drfilter** [comment]
命令行版本，一轮 748.49 秒，确实快了很多。
