### ISSUE TITLE
Convert python to xlearn data structures without temp files

### ISSUE THREAD

**Issue by gsakkis** [aksnzhy/xlearn#130]
I'm wondering how hard would it be to convert Python data (numpy or scipy.sparse arrays) to xlearn data structures directly, without having to save and load intermediate temp files. This is especially important if one wants to call `predict` for single feature vectors (e.g. exposed as a API on a server) instead of whole test datasets.

**Comment by randxie** [comment]
Hi @gsakkis, there is an utility function provided to convert numpy array to libffm format that can be consumed by predict method (write_data_to_xlearn_format). But it still requires writing to external file. I believe the in-memory conversion is an on-going work (please correct me if I am wrong @aksnzhy).
