### ISSUE TITLE
install issue for python interface

### ISSUE THREAD

**Issue by jyuan1986** [aksnzhy/xlearn#15]
Hi:
I've successfully built exectuable and lib/ folder. Then I go to python-package/ folder under build/ folder and run install-python.sh. And it shows everything is OK. 
However, when I tried to run "test_python.py", it gave me an error " module 'xlearn' has no attribute 'create_ffm'". It seems the installed python package failed to find the correct python module. Do you have any solution for this issue? 

Thanks!
Fenglin

**Comment by aksnzhy** [comment]
For some platforms，you need to exprort the PYTHONPATH to your .bashrc . You can see the details in install page. Thank you！

**Comment by jyuan1986** [comment]
It works. I seems I export the wrong path. 
Thanks:)
