### ISSUE TITLE
ffm 尚不支持类似scikit-learn的API？

### ISSUE THREAD

**Issue by eric-Rstats** [aksnzhy/xlearn#152]
hi,
  xlearn用起来确实很不错。不过目前看起来类似scikit-learn的写法，调用ffm的demo实际上还是类似文件读写的操作？这是由于目前只支持libffm格式的原因吗？然后未来是否python API这部分会考虑改良这种输出model.out，之后读入的形式，因为对jupyter notebook还不友好。
   然后看起来FMModel这块还有部分的methods会更新？

Thank you for your work! Best Regards!

Eric

**Comment by aksnzhy** [comment]
@eric-Rstats Hi, 目前 xLearn 的数据操作都是通过中间文件来完成的。我最近在做 Python 对 DMatrix 的接口，未来就可以直接通过 Python API 操作数据，不需要经过中间文件。

**Comment by eric-Rstats** [comment]
Thank you!也就是scikit这种写法，目前ffm还不太能用是吗？
