### ISSUE TITLE
Segmentation fault (core dumped) when convert text file to binary file

### ISSUE THREAD

**Issue by ylkky** [aksnzhy/xlearn#157]
I had moved some features and their value from my libfm file, then the process of "Convert text file to binary file"  failed with "Segmentation fault (core dumped)".
The original file is still work well.
How can I see where is the problem of my new file?

**Comment by aksnzhy** [comment]
@ylkky I think this issue comes from the incorrect file format when changing the original libfm file. You can try to check the format carefully. For example, missing ' ' or '\n', etc.

**Comment by ylkky** [comment]
I try to move these values from the original csv file, and convert it to libfm by a tool used before (and the convert tool works no error in the original csv file).
Now, I try to reduce the size of my data file. But the error occurs at the beginning( The size of bin file is still 0). And the first line of my libfm file is:
`1 54:2 172:0.0871 274:2.3 276:2 277:5 278:4.2 279:30 280:3 647:0.5462962962962963 731:0.19444444444444445 734:0.2962962962962963
`
The first 10 lines are shown as below:
![image](https://user-images.githubusercontent.com/19553921/46143811-b35a0a80-c28d-11e8-9487-b74701d2cb51.png)
I think the format is correct....

**Comment by aksnzhy** [comment]
@ylkky Can you send you data (or a small copy) to my EMail: mctt90@gmail.com ? I can help you to check out the error.

**Comment by aksnzhy** [comment]
@ylkky Hi, there are three lines of data in your file only has a label but not have the feature. I removed these lines and it works well.

**Comment by nenetto** [comment]
Just in case anyone like me arrived here looking for a solution:

I was trying to predict over a data set where not all rows have representation of all the fields. This made my python kernel die with any further information.

The problem was  the [instance-wise normalization](https://xlearn-doc.readthedocs.io/en/latest/python_api/#instance-wise-normalization). If you just remove the default behaviour, it does not crush such in my usecase:

```python
ffm = xlearn.create_ffm()
ffm.setTest('./data/scoring.ffm') 

# Start to predict
ffm.disableNorm()
ffm.setSigmoid()
scores = ffm.predict('./data/model_complete.bin')
```
