### ISSUE TITLE
训练好的二进制模型文件，如何转化成文本文件呢？反过来呢？

### ISSUE THREAD

**Issue by ymkigeg** [aksnzhy/xlearn#183]

**Comment by aksnzhy** [comment]
@ymkigeg 二进制文件和文本文件不能直接相互转化，都是通过 xLearn 内部的 API 生成的，具体请参见文档。谢谢～

**Comment by ymkigeg** [comment]
明白，所以最好的办法是 训练前调用 setTXTModel，使得二进制文件和文本文件都生成了，这样两个都能用

**Comment by aksnzhy** [comment]
对的 是这样的
