### ISSUE TITLE
does the race condition exist when update the parameters of model?

### ISSUE THREAD

**Issue by DevHaufior** [aksnzhy/xlearn#185]
https://github.com/aksnzhy/xlearn/blob/595902cd1bea4b5700ab45dbdcabb23ac9d97ee5/src/base/thread_pool.h#L102

Hello, I doubt that there exists a race condition when more than one thread deal rows to update the parameters at the some time.Maybe I am wrong with this, since I am a fresh C++ user.

**Comment by aksnzhy** [comment]
@DevHaufior Hi, xLearn uses lock-free learning, which doesn't use lock when updating model parameters. Is is also called ``Hogwild!`` algorithm, which can speedup training process without accuracy lose when data is sparse.

**Comment by DevHaufior** [comment]
I see,em...m，it looks like a little bit violent.
