### ISSUE TITLE
设置验证集训练的结果和不设置验证集训练的结果不一样

### ISSUE THREAD

**Issue by sunjiaxin111** [aksnzhy/xlearn#186]
当我先用验证集测出最优轮数，再不用验证集直接迭代这个轮数，两者导出的model.txt文件不一致；

**Comment by aksnzhy** [comment]
@sunjiaxin111 xLearn 可能会在不同的训练过程中有一些微小的不一致（nondeterministic），这是由于 Lock-free 训练导致的。你需要检测一些这个不一致只是 weight 数值上的不一致，还是模型 accuracy 差了很多。

**Comment by sunjiaxin111** [comment]
@aksnzhy thanks
