### ISSUE TITLE
我在训练时用k=2,4,8,16时，训练效果怎么是一样的？

### ISSUE THREAD

**Issue by sunjiaxin111** [aksnzhy/xlearn#187]
如题

**Comment by aksnzhy** [comment]
@sunjiaxin111 Can you share me your code ? I will try to find where is going wrong.

**Comment by sunjiaxin111** [comment]
@aksnzhy 
![image](https://user-images.githubusercontent.com/13600388/49777659-5e7e4a00-fd3c-11e8-99df-c2c65b56f4e6.png)
当我修改k值时，效果不变

**Comment by aksnzhy** [comment]
@sunjiaxin111  我在我这里测试是没有问题，你可以看看设置不同的 k 会不会对模型大小产生影响，如果大小改变了，说明 k 起了做作用。有可能对于你的数据，这些 k 值对结果影响不大。

```
[ ACTION     ] Initialize model ...
[------------] Model size: 390.28 KB
```

**Comment by sunjiaxin111** [comment]
@aksnzhy 可能是K值影响不大
