### ISSUE TITLE
训练完FFM模型后，在预测时，如果测试集中出现了在训练集中没出现的index,怎么办？

### ISSUE THREAD

**Issue by sunjiaxin111** [aksnzhy/xlearn#191]
如题，此时模型是怎么预测的？

**Comment by sunjiaxin111** [comment]
![image](https://user-images.githubusercontent.com/13600388/49921236-e2286a00-fee7-11e8-8a0e-45076ce37821.png)
比如这里的index_1在训练集中没有出现过，而在测试集中出现了，那么在预测时，index_1无法在FFM模型中找到对应的隐向量，然后模型是怎么做的?默认值？

**Comment by aksnzhy** [comment]
@sunjiaxin111 目前 xLearn 的做法是自动忽略掉在训练集没有出现的 feature .

**Comment by sunjiaxin111** [comment]
@aksnzhy 谢谢
