### ISSUE TITLE
Why is xlearn CPU utilization so low

### ISSUE THREAD

**Issue by payne4handsome** [aksnzhy/xlearn#208]
I used 48 cores cpu and 90g memory to train by train, but why cpu utilization so low? The details show below
![image](https://user-images.githubusercontent.com/28085731/51360848-54542600-1b08-11e9-85a0-c3ba58bd4336.png)
![image](https://user-images.githubusercontent.com/28085731/51360866-62a24200-1b08-11e9-9b01-34d88876e79c.png)

**Comment by aksnzhy** [comment]
@payne4handsome Hi, can you show your code here? Which way you choose to use xLearn, the cmd line or Python API?

**Comment by payne4handsome** [comment]
I used cmd line. Cmd are as follows:
```
nohup xlearn_train ./train_sample/sample.txt -s 1 -v  ./validation_sample/x09  -x acc  -e 200  -b 0.00002 -r 0.2  -k 4  -block 50000 --disk -sw 2 2>&1 &
```
