### ISSUE TITLE
Test_AUC gives -nan when training FFM model on the full dataset of "criteo"

### ISSUE THREAD

**Issue by matricer** [aksnzhy/xlearn#217]
![default](https://user-images.githubusercontent.com/16053879/52047854-d51c1480-2541-11e9-8459-3db8ac4091a4.png)

**Comment by aksnzhy** [comment]
@matricer Hi, thanks for your feedback. I'll check this issue as soon as possible.

**Comment by matricer** [comment]
@aksnzhy Hi, I go through the validation dataset generated by [this code](https://github.com/guestwalk/kaggle-2014-criteo) and find that there is no positive sample. I think this is the problem which makes auroc "-nan"
