### ISSUE TITLE
Data random shuffling for every epoch will benefit the performance. Will this feature be supported in the feature?

### ISSUE THREAD

**Issue by matricer** [aksnzhy/xlearn#224]

**Comment by aksnzhy** [comment]
@matricer Hi, xLearn will shuffle data for every by default.

**Comment by matricer** [comment]
nice~
By the way, data shuffling will be done in both the "momery-only" case and the "momery-and-disk" case?

**Comment by aksnzhy** [comment]
@matricer Hi, data shuffling will only be used for in-memory training. It is too expensive to shuffle data on disk.

**Comment by matricer** [comment]
ok, thanks
