### ISSUE TITLE
PermissionError when running in a jupyter notebook

### ISSUE THREAD

**Issue by jcr-lyxor** [aksnzhy/xlearn#234]
There is an issue when running the iris example in sklearn api in jupyter: 

`PermissionError: [Errno 13] Permission denied`

It is actually because of  `tempfile.NamedTemporaryFile(delete=True)` in _sklearn.py. Maybe one explanation is [here](https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file). Anyway, it is working by setting `delete=False`

**Comment by etveritas** [comment]
@jcr-lyxor  Yes, it will occurs this error on windows when using sklearn API, and we are checking the more reasons, so we don't suggest use sklearn api now, we will improve it as soon as possible.

**Comment by jcr-lyxor** [comment]
It is working with the hack. Even is it is not perfect I need the skleran api so unless it returns wrong result I just use delete=False.
Thanks

**Comment by etveritas** [comment]
@jcr-lyxor Hello, we have fixed this error, you can download the latest source code.

**Comment by jcr-lyxor** [comment]
Great thanks.
