### ISSUE TITLE
@vincenhe

### ISSUE THREAD

**Issue by JohnWill6** [aksnzhy/xlearn#241]
@vincenhe 

I update the model output like this, you need to git clone the source code and re-build it: 

Linear: 

  bias: 0
  i_0: 0
  i_1: 0
  i_2: 0
  i_3: 0

FM: 

  bias: 0
  i_0: 0
  i_1: 0
  i_2: 0
  i_3: 0
  v_0: 5.61937e-06 0.0212581 0.150338 0.222903
  v_1: 0.241989 0.0474224 0.128744 0.0995021
  v_2: 0.0657265 0.185878 0.0223869 0.140097
  v_3: 0.145557 0.202392 0.14798 0.127928

FFM: 

  bias: 0
  i_0: 0
  i_1: 0
  i_2: 0
  i_3: 0
  v_0_0: 5.61937e-06 0.0212581 0.150338 0.222903
  v_0_1: 0.241989 0.0474224 0.128744 0.0995021
  v_0_2: 0.0657265 0.185878 0.0223869 0.140097
  v_0_3: 0.145557 0.202392 0.14798 0.127928
  v_1_0: 0.219158 0.248771 0.181553 0.241653
  v_1_1: 0.0742756 0.106513 0.224874 0.16325
  v_1_2: 0.225384 0.240383 0.0411782 0.214497
  v_1_3: 0.226711 0.0735065 0.234061 0.103661
  v_2_0: 0.0771142 0.128723 0.0988574 0.197446
  v_2_1: 0.172285 0.136068 0.148102 0.0234075
  v_2_2: 0.152371 0.108065 0.149887 0.211232
  v_2_3: 0.123096 0.193212 0.0179155 0.0479647
  v_3_0: 0.055902 0.195092 0.0209918 0.0453358
  v_3_1: 0.154174 0.144785 0.184828 0.0785329
  v_3_2: 0.109711 0.102996 0.227222 0.248076
  v_3_3: 0.144264 0.0409806 0.17463 0.083712

_Originally posted by @aksnzhy in https://github.com/aksnzhy/xlearn/issues/149#issuecomment-421755171_

**Comment by JohnWill6** [comment]
使用FFM选出的特征，比如v_3_1: 0.154174 0.144785 0.184828 0.0785329，v_3_0: 0.055902 0.195092 0.0209918 0.0453358，怎么比较v_3_1、v_3_0两个组合特征的重要性呢，有类似xgboost的 feature importance 评价指标吗？

**Comment by etveritas** [comment]
@JohnWill6 现在还没有给出feature importance 评价指标接口。

**Comment by JohnWill6** [comment]
我在训练FM时设置了lambda=0.2，那么用下面的公式predict时，怎么将lambda参与到计算中呢，望指教，十分感谢！
def pre(X, v, w):
    reg_lambda = 0.2 #如何使用？？
    # xi·vi,xi与vi的矩阵点积
    inter_1 = X * v
    # xi与xi的对应位置乘积   与   xi^2与vi^2对应位置的乘积    的点积
    inter_2 = multiply(X, X) * multiply(v, v)  # multiply对应元素相乘
    # 完成交叉项,xi*vi*xi*vi - xi^2*vi^2
    interaction = sum(multiply(inter_1, inter_1) - inter_2) / 2.
    # 计算预测的输出
    p = bias + X * w + interaction 
    y_hat = 1.0 / (1 + exp(-p))
    return y_hat

**Comment by JohnWill6** [comment]
我在训练FM时设置了lambda=0.2，那么用下面的公式predict时，怎么将lambda参与到计算中呢，望指教，十分感谢！
def pre(X, v, w):
reg_lambda = 0.2 #如何使用？？
# xi·vi,xi与vi的矩阵点积
inter_1 = X * v
# xi与xi的对应位置乘积 与 xi^2与vi^2对应位置的乘积 的点积
inter_2 = multiply(X, X) * multiply(v, v) # multiply对应元素相乘
# 完成交叉项,xivixivi - xi^2vi^2
interaction = sum(multiply(inter_1, inter_1) - inter_2) / 2.
# 计算预测的输出
p = bias + X * w + interaction
y_hat = 1.0 / (1 + exp(-p))
return y_hat @etveritas @

**Comment by JohnWill6** [comment]
我在训练FM时设置了lambda=0.2，那么用下面的公式predict时，怎么将lambda参与到计算中呢，望指教，十分感谢！
`def pre(X, v, w):
reg_lambda = 0.2 #如何使用？？
# xi·vi,xi与vi的矩阵点积
inter_1 = X * v
# xi与xi的对应位置乘积 与 xi^2与vi^2对应位置的乘积 的点积
inter_2 = multiply(X, X) * multiply(v, v) # multiply对应元素相乘
# 完成交叉项,xivixivi - xi^2vi^2
interaction = sum(multiply(inter_1, inter_1) - inter_2) / 2.
# 计算预测的输出
p = bias + X * w + interaction
y_hat = 1.0 / (1 + exp(-p))
return y_hat`
@etveritas

**Comment by etveritas** [comment]
@JohnWill6 ``reg_lambda``是用在目标函数中，用来减少优化过程中的overfitting，而非用在计算预测值中。目标函数大概这个样子，``Obj = Loss(y,y_hat) + 1/2*reg_lambda*w^2``，优化时，求个偏导就是``partition_gradient+reg_lambda*w``，其中``w``是参数。

**Comment by JohnWill6** [comment]
好的，我在看看源码，非常感谢！
