### ISSUE TITLE
run_example failed in MacOS

### ISSUE THREAD

**Issue by cuiwow** [aksnzhy/xlearn#246]
I installed a **new** version with the **build.sh** in MacOS (Xcode and CMake installed first). 
When running the **run_example.sh**, it aborted with the error message:
![image](https://user-images.githubusercontent.com/3415190/56015304-2824fb80-5d2b-11e9-8b42-40720f029d9b.png)

MacOS: Mojave 10.14.4
xlearn: 0.43

(the pip installed one in version 0.40a works on my computer, but has a bug just fixed in latest version)

**Comment by aksnzhy** [comment]
@cuiwow I find the same error. You can solve the problem by do this:

mkdir a `build` outside the xlearn source code:

```
cmake ../xlearn
make -j4
```
 and then you can try the demo successfully.

I will figure out why this error come out. Thanks!

**Comment by aksnzhy** [comment]
@cuiwow I fixed the bug and you can use the latest code to test it.  Thank you!

**Comment by cuiwow** [comment]
@aksnzhy Thanks, that works.

You have to agree with the xcode agreement before using /usr/bin/cc, otherwise it would throw an exception. I don't know whether it is the reason, and how i could install it before without /usr/bin/cc.

**Comment by cuiwow** [comment]
@aksnzhy  Another case:   failed with my own data, the same error message.
Line size is about 2.1MB, 
csv file format: label,value0,value1...   label is a int 0/1, while values are binary float 0.0/1.0

It works when using just 10 values. But failed using real data with more than 500,000 columns, as the attached file.
I have checked the columns' number, and each element is an integer or float number.
[fm_train.txt](https://github.com/aksnzhy/xlearn/files/3072251/fm_train.txt)

**Comment by aksnzhy** [comment]
@etveritas Could you please help @cuiwow to solve this issue? Thanks!

**Comment by etveritas** [comment]
@aksnzhy okay, and @cuiwow, I'll try to solve this issue, please give me a minute.

**Comment by etveritas** [comment]
@aksnzhy There is another ``kMaxLineSize`` left unchange before, and I have modified it. @cuiwow after change this constant, I test on WSL with your data, it passed.

**Comment by cuiwow** [comment]
@aksnzhy @etveritas 
Thanks a lot. I have success in running a demo. Then encountered another problem...
I have a line size of 2MB. Industry recommendation datasets always have more than 1M lines, or 10M lines at least. The total data size would be larger than 2TB. I want to train it on a single server, to build a baseline. But my disk is not large enough..
I think the data should be processed into the right format batch by batch during training, not whole data. 
Thanks for your efforts.

**Comment by etveritas** [comment]
@cuiwow For large dataset, xLearn have supported ``on-disk`` train if your machine have enough memory, you can find mode in https://xlearn-doc.readthedocs.io/en/latest/large/index.html. And if you have not enough disk, you can buy more...
