### ISSUE TITLE
XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

### ISSUE THREAD

**Issue by gongtian1234** [aksnzhy/xlearn#247]
在windows下安装的，已经安装好GCC和CMAKE，然后用pip install xlearn安装，安装完成后，在导入时报错，错误如题所示，请问怎么解决

**Comment by etveritas** [comment]
Windows下的安装请参考这里：https://xlearn-doc.readthedocs.io/en/latest/install/install_windows.html

**Comment by gongtian1234** [comment]
> Windows下的安装请参考这里：https://xlearn-doc.readthedocs.io/en/latest/install/install_windows.html 或 https://xlearn-doc-cn.readthedocs.io/en/latest/install/install_windows.html

你好，必须安装Visual Studio 2017吗，安装了Visual Studio Profession 2015和GCC不行吗

**Comment by etveritas** [comment]
@gongtian1234 我在本机上用VS2017开发的。我曾在一个免费CI上的VS2015测试过，没有编译通过，应该是里面的C++ Tools(或MS Build)版本有些低，可以尝试升级一下VS的这些组件。关于其他的编译器，MinGW还有Clang等确实没编译测试过。最后，从源码编译的话，编译完成之后应该切换到的构建(``build``)目录的``python-package``的目录下面，用管理员权限运行命令``python setup.py install``来进行xLearn Python库的安装。我们会尽快更新PYPI上的版本，也就是用``pip``命令直接安装的版本。
这里是一个最近编译的 __非官方版本__ 的whl文件https://ci.appveyor.com/project/etveritas/xlearn/builds/23831797/artifacts 你可以尝试使用。

**Comment by gongtian1234** [comment]
> @gongtian1234 我在本机上用VS2017开发的。我曾在一个免费CI上的VS2015测试过，没有编译通过，应该是里面的C++ Tools(或MS Build)版本有些低，可以尝试升级一下VS的这些组件。关于Windows系统的其他编译器MinGW等确实没编译测试过。最后，从源码安装的话，编译完成之后应该切换到构建(`build`)目录的`python-package`目录下面，用管理员权限运行命令`python setup.py install`来进行xLearn Python库的安装。我们会尽快更新PYPI上的版本，也就是用`pip`命令直接安装的版本。
> 这里是一个最近编译的 **非官方版本** 的whl文件https://ci.appveyor.com/project/etveritas/xlearn/builds/23831797/artifacts 你可以尝试使用。
> 还有一件事，最新的版本需要你的Python安装了NumPy和Pandas库。

非常感谢你的耐心解答，从你发来的非官方链接下载了重新安装后成功了，非常感谢
