### ISSUE TITLE
Feature index is too large (overflow).

### ISSUE THREAD

**Issue by wuminbin** [aksnzhy/xlearn#255]
My libffm file contains two fields that has more than 10000 ids. So when trainning it crash, can I make it work?

**Comment by aksnzhy** [comment]
@wuminbin  FFM algorithm will spend much bigger memory cost than other models. If your model is larger than your memory, nothing can help it. If the model + data is larger than memory, you can try to use on-disk training, which will not load all the data to memory for training.

**Comment by wuminbin** [comment]
I see, my svmlight file is not in ordered index. For that reason, I recommend you to check the data format.
