### ISSUE TITLE
模型预测的时候不能控制线程的个数吗?

### ISSUE THREAD

**Issue by fly12357** [aksnzhy/xlearn#264]

**Comment by aksnzhy** [comment]
@fly12357 可以的，在命令行模式下用 `-nthread`,  在 python 下用 `nthread` 参数。

**Comment by fly12357** [comment]
> @fly12357 可以的，在命令行模式下用 `-nthread`,  在 python 下用 `nthread` 参数。

感谢回复, 但是我在命令行预测的时候出现了下面的情况~

![image](https://user-images.githubusercontent.com/40494145/58757448-57900180-853f-11e9-8447-8227b0e44dc7.png)

**Comment by fly12357** [comment]
> @fly12357 可以的，在命令行模式下用 `-nthread`,  在 python 下用 `nthread` 参数。

非常感谢回复, 但是我在命令行下使用模型预测,出现下面的情况

![image](https://user-images.githubusercontent.com/40494145/58757610-ba829800-8541-11e9-810f-344519fbb2f6.png)

**Comment by etveritas** [comment]
@aksnzhy Do we miss the value setting in [this part](https://github.com/aksnzhy/xlearn/blob/master/src/solver/solver.cc#L404-L405)?
It should be
```C++
  size_t threadNumber = std::thread::hardware_concurrency();
  if (hyper_param_.thread_number != 0) {
    threadNumber = hyper_param_.thread_number;
  }
  pool_ = new ThreadPool(threadNumber);
```

**Comment by fly12357** [comment]
> @aksnzhy Do we miss the value setting in [this part](https://github.com/aksnzhy/xlearn/blob/master/src/solver/solver.cc#L404-L405)?
> It should be
> 
> ```c++
>   size_t threadNumber = std::thread::hardware_concurrency();
>   if (hyper_param_.thread_number != 0) {
>     threadNumber = hyper_param_.thread_number;
>   }
>   pool_ = new ThreadPool(threadNumber);
> ```
> 
> And could you hava a try by changing to these lines, then rebuild it?@fly12357

It works, Thank you~
