### ISSUE TITLE
训练过程异常中断

### ISSUE THREAD

**Issue by PrimaryKey** [aksnzhy/xlearn#269]
**运行了一下Scikit-learn API的简例：**
`
iris_data = load_iris()
X = iris_data['data']
y = (iris_data['target'] == 2)

X_train,   \
X_val,     \
y_train,   \
y_val = train_test_split(X, y, test_size=0.3, random_state=0)

linear_model = xl.LRModel(task='binary', init=0.1,
                          epoch=10, lr=0.1,
                          reg_lambda=1.0, opt='sgd')

linear_model.fit(X_train, y_train,eval_set=[X_val, y_val],is_lock_free=False)

y_pred = linear_model.predict(X_val)
`
**每次运行到fit的时候就会中断，是怎么回事？
jupyter notebook会提示服务器中断，即将重启；
pycharm不报错，直接正常结束，但是fit后边的代码都没有执行(如下)；**

_...
[ ACTION     ] Early-stopping at epoch 8, best AUC: 0.994652
[ ACTION     ] Start to save model ...

Process finished with exit code -1073740791 (0xC0000409)_

**Comment by aksnzhy** [comment]
@etveritas Could you please look at this issue?

**Comment by etveritas** [comment]
@aksnzhy okay, I'll check soon.

**Comment by etveritas** [comment]
@PrimaryKey Hi, could you provide your xLearn version and OS version?

**Comment by PrimaryKey** [comment]
> @PrimaryKey Hi, could you provide your xLearn version and OS version?

python 3.6.8 (in anaconda3)
xlearn 0.44
windows 10
