### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [aksnzhy/xlearn#293]
Hi, thanks for this awesome library! Thanks to the C API, there are now [Ruby bindings](https://github.com/ankane/xlearn) for xLearn. Feel free to create an issue on the project if you have any feedback.

A few notes:
- The C API is really clean and easy to follow 🎉 
- It'd be great if there was an option to turn off all output https://github.com/aksnzhy/xlearn/issues/124
- LightGBM distributes [shared libraries](https://github.com/microsoft/LightGBM/releases) (`so`, `dylib`, `dll`) with releases, which makes it easier to vendor in projects (something to consider)

I also submitted a pull request to Homebrew to make installation even faster/easier on Mac: https://github.com/Homebrew/homebrew-core/pull/45216

**Comment by aksnzhy** [comment]
@ankane Thanks so much for the Ruby bindings and homebrew installation. It will be great if you can contribute the ruby binding to the xLearn master branch!

**Comment by ankane** [comment]
No problem. I think it'll be easier to manage as a separate project, but could add a link in the docs (not sure where the best place would be).

**Comment by ankane** [comment]
Hey @aksnzhy, I received some feedback from the Homebrew team. It looks like `make install` doesn't currently install the binaries (`xlearn_train` and `xlearn_predict`) or the shared library (`libxlearn_api.dylib`). What are your thoughts about including this in `make install`?

**Comment by ankane** [comment]
Hey @aksnzhy, I just wanted to let you know that xLearn is now available on Homebrew, so Mac users can do:

```sh
brew install xlearn
```

fwiw, the `make install` situation was brought up but wasn't a blocker, but still think it would be good to address in a future version.
