### ISSUE TITLE
The small test file output is not between 0 and 1?

### ISSUE THREAD

**Issue by lihongqiang** [aksnzhy/xlearn#30]
I run the scripts in the install md file:
./xlearn_train ./small_train.txt -v ./small_test.txt -s 2
./xlearn_predict ./small_test.txt ./small_train.txt.model

but I check the output file small_test.txt.out, I find the outputs are not in range 0 and 1.
  1 -1.64431
  2 -0.561951
  3 -0.789286
  4 -0.540316
  5 -1.27843
  6 -0.996344
  7 -1.17249
  8 -1.60885
  9 -0.73878
 10 -1.19467
Is there any other param that I can add to solve the problem? I also run the codes in python, but got the same output. I also run the libffm with the same data, but got outputs between 0 and 1.
 1 0.197887
  2 0.363382
  3 0.364715
  4 0.3575
  5 0.276505
  6 0.332071
  7 0.471544
  8 0.177905
  9 0.323288
 10 0.232038

**Comment by aksnzhy** [comment]
On default, xlearn will just out the score. If you want your output between 0 ~ 1, please add the `--sigmoid` option when using xlearn_predict. Or using setSigmoid() function when using python interface.

**Comment by HyperGroups** [comment]
@aksnzhy 
hi, Can I dump the model to get the txt weights and bias to predict use my own function now? or this functionality is on roadmap

**Comment by aksnzhy** [comment]
Now, the model will be dump to disk in binary data. I think the binary data is too large.
