### ISSUE TITLE
[Idea] Implicit feedback collaborative filtering

### ISSUE THREAD

**Issue by ankane** [aksnzhy/xlearn#301]
Hi, I think xLearn can be a great tool for recommender systems. It works great for explicit feedback following [this approach](https://www.jefkine.com/recsys/2017/03/27/factorization-machines/) with both FM and FFM.

I was wondering if you'd consider supporting implicit feedback (one-class matrix factorization). Here are a few papers on the topic:

- FM
    - [Factorization Machines for Datasets with Implicit Feedback](https://arxiv.org/pdf/1812.08254.pdf)
    - [Optimizing Factorization Machines for Top-N Context-Aware Recommendations](https://fajieyuan.github.io/papers/WISE2016.pdf)
    - [BoostFM: Boosted Factorization Machines for Top-N Feature-based Recommendation](http://wnzhang.net/papers/boostfm.pdf)
- FFM
    - [One-class Field-aware Factorization Machines for Recommender Systems with Implicit Feedbacks](https://www.csie.ntu.edu.tw/~cjlin/papers/ocffm/imp_ffm.pdf)

Related to #230

**Comment by sumitsidana** [comment]
Hi @ankane thanks for sharing these resources, but, just curious can't the problem of implicit feedback be reduced to binary classification by doing negative sampling and then applying the original FM or FFM implementation?

**Comment by ankane** [comment]
Hi @sumitsidana, thanks for the response. Unfortunately, I'm not super familiar with the topic, so don't know the answer to that question.

I've noticed some MF (not FM) libraries like [libmf](https://github.com/cjlin1/libmf) use a different approach for implicit feedback than explicit feedback (I believe performance is a factor), so not sure if something like that applies here. If not, maybe there could be built-in support for the approach mentioned above.

Sorry, this is probably one of my least helpful responses on GitHub.
