### ISSUE TITLE
FFM模型输出的一阶项weight的数量跟特征取值数量相同？

### ISSUE THREAD

**Issue by Anncastle** [aksnzhy/xlearn#346]
如题，应该是有9个field，一阶项应该有9个，但是却输出了300多个（跟特征取值数量相同）的一阶项，求解决
我的libffm数据格式：
![image](https://user-images.githubusercontent.com/33474645/92084845-8c51cf00-edfa-11ea-9f51-25167cd9b1ba.png)

model.txt的输出：
![image](https://user-images.githubusercontent.com/33474645/92084789-79d79580-edfa-11ea-8210-633eebd45494.png)

**Comment by 1030617255** [comment]
请问您是怎么生成的ffm文件的，使用他的api吗？

**Comment by 1030617255** [comment]
关于一阶项个数，他的维度和交叉项的个数是一样的，只不过交叉项的第二维会比他多，可以去看一下ffm的表达式就知道了。

**Comment by youess** [comment]
建议去理解下fm的再来提问，模型看到的特征值是你ffm格式中的hash值个数，不是field个数。 @Anncastle

**Comment by Anncastle** [comment]
> 建议去理解下fm的再来提问，模型看到的特征值是你ffm格式中的hash值个数，不是field个数。 @Anncastle

@youess 给的demo里的例子一阶项就是几个特征几个weight，有什么问题？FM跟FFM的一阶项没任何区别吧，几个特征就是几个weight呀

**Comment by Anncastle** [comment]
> 关于一阶项个数，他的维度和交叉项的个数是一样的，只不过交叉项的第二维会比他多，可以去看一下ffm的表达式就知道了。

@1030617255 表达式的一阶项不就是wixi?所以有几个xi就有几个wi...我理解就是模型有几个输入特征，就有几个wi，而不是输入特征有多少取值，就有多少wi

**Comment by Anncastle** [comment]
> 建议去理解下fm的再来提问，模型看到的特征值是你ffm格式中的hash值个数，不是field个数。 @Anncastle

@youess 我重新看了一下，稍微理解了一下，所以FM里面的特征其实是说原始的类别特征做过one-hot之后来算的特征吗

**Comment by Anncastle** [comment]
> 请问您是怎么生成的ffm文件的，使用他的api吗？

@1030617255 自己写，api里没有

**Comment by Anncastle** [comment]
> 关于一阶项个数，他的维度和交叉项的个数是一样的，只不过交叉项的第二维会比他多，可以去看一下ffm的表达式就知道了。

@1030617255 我理解了，谢谢，因为FM和FFM都对类别进行了one-hot，close了
