### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by ankane** [aksnzhy/xlearn#354]
Hi, thanks for this great library!

Currently, a few files (`model_parameters.cc`, `fm_score.cc`, and `ffm_score.cc`) depend on SSE, which isn't available on arm64 (used by the new M1 Macs). It'd be nice if there was support for ARM in the future.

`model_parameters.cc` compiles with:

```cc
#if defined(__SSE__)
#include <pmmintrin.h>  // for SSE
#endif
```

but it looks like `fm_score.cc` and `ffm_score.cc` need larger changes.

**Comment by fxcoudert** [comment]
This was not completed :(
