### ISSUE TITLE
Ubuntu16.04 install-python.sh

### ISSUE THREAD

**Issue by colindj** [aksnzhy/xlearn#38]
When I install the python environment,Hints “ImportError: No module named setuptools” where "from setuptools import setup, find_packages".
The problem is “sudo python setup.py install” Instead “python setup.py install”，Missing library at this time,So you need to copy “libxlearn.so” to the current directory.install-python.sh can be modified as follows:

#!/bin/bash
cp ../build/libxlearn.so .
python setup.py install

**Comment by aksnzhy** [comment]
@purkyston Can you check out this problem ?

**Comment by aksnzhy** [comment]
@colindj You cannot run ./install-python.sh in the source code. You need to do it in your build directory. Actually, you can just use ./build.sh in our latest code to do all the things.

**Comment by colindj** [comment]
@aksnzhy I not  run ./install-python.sh in the source code directory.Actually,I run ./install-python.sh in python-package.So it's the same as in the source code directory to run ./build.sh.

**Comment by aksnzhy** [comment]
@colindj The build.sh will automatically create a directory called build. If you want to build xlearn by yourself, you also need to create a build directory and type cmake and make. After that, you can go to the python-package in build (not in source code) and install it.

**Comment by colindj** [comment]
@aksnzhy Yes, I do the work by myself. It's not really hard.
