### ISSUE TITLE
Correct way to represent missing data

### ISSUE THREAD

**Issue by alexklibisz** [aksnzhy/xlearn#47]
Hi, can you tell me what's the correct way to represent missing values in the libsvm or libffm formats? For example, if you had a feature `gender` with values `male`, `female` or `missing`, how would you represent the `missing` value?

**Comment by aksnzhy** [comment]
First you need to assign a feature id for gender. For example ，if the feature id is 5，now 5:0 can represent male and 5:1 can represent female. If this feature is missing，many ways you can choose to solve this problem . The easiest way is that you can represent missing as a special value like 5:2.

**Comment by alexklibisz** [comment]
@aksnzhy Thanks for the quick response. Would it be an error if I just leave out the field?

**Comment by aksnzhy** [comment]
No error happens if you just leave out the field :)
