### ISSUE TITLE
cmake version > 3.0 ?

### ISSUE THREAD

**Issue by xxyy1** [aksnzhy/xlearn#52]
when I install from pip , 
Exception: Please install CMake first
but  I  the centOS has cmake  2.8.12.2

when I  build from source code
./build.sh
CMake Error at CMakeLists.txt:24 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

can have a simple way install xlearn ?
or have a simple way update cmake to 3.0

**Comment by aksnzhy** [comment]
@xxyy1 Hi, you can follow this page to update your CMake. http://xlearn-doc.readthedocs.io/en/latest/install_cmake.html

**Comment by xxyy1** [comment]
install cmake
Loaded plugins: changelog, priorities
942 packages excluded due to repository priority protections
Package cmake-2.8.12.2-2.el7.x86_64 already installed and latest version
Nothing to do

**Comment by aksnzhy** [comment]
Because xLearn requires CMake version > 3.0, so you get this exception.  

We changed our CMake minimal requirement to 2.8. Now you can try to build it from source code.

**Comment by xxyy1** [comment]
build from source code 
new error
----------------------------
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lstdc++
/bin/ld: cannot find -lm
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [test/base/file_util_test] Error 1
make[1]: *** [src/base/CMakeFiles/file_util_test.dir/all] Error 2
make: *** [all] Error 2
/bin/python2
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "xlearn/libpath.py", line 45, in find_lib_path
    'Cannot find xlearn Library in the candidate path'
__builtin__.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

**Comment by aksnzhy** [comment]
Why your compiler does not support the standard library? Can you find these libraries like pthread on your machine?

**Comment by xxyy1** [comment]
sorry,
This is the first time to meet this problem.
What path to look for, what to find？
How to solve this problem？

**Comment by aksnzhy** [comment]
Don't worry, can you tell me what OS on your computer? OSX or Linux ?

**Comment by xxyy1** [comment]
CentOS Linux release 7.4.1708 (Core)

**Comment by xxyy1** [comment]
Thank you very much for your patience guidance.

**Comment by aksnzhy** [comment]
It seems that your OS missing some necessary libraries. 

Please try the following command:

`sudo yum install glibc-static libstdc++-static -y`

and then try to build xLearn again.  There there is still some problems, please share me the error information.

**Comment by xxyy1** [comment]
it works! thank you very much~~
