### ISSUE TITLE
Does xlearn support the number of multithreading?

### ISSUE THREAD

**Issue by xxyy1** [aksnzhy/xlearn#53]
like param "nthread"  in xgboost 
I don't want to be full of CPU every time

**Comment by aksnzhy** [comment]
It's a good feature. We will update our code to support it in these days.

**Comment by aksnzhy** [comment]
@xxyy1 Hi, now you can use -nthread option in command line. We will update the python API as soon as possible.

**Comment by xxyy1** [comment]
Very fast！
now,any other parameters that can be replaced  ,the python API

**Comment by aksnzhy** [comment]
@xxyy1 Hi, we have already updated the Python API. You can use the nthread param like this:

`param = { 'task':'binary',
                   'lr' : 0.2,
                  'lambda' : 0.002,
                  'metric' : 'acc' ,
                  'nthread' : 2 }`

**Comment by xxyy1** [comment]
it works! thanks~~
