### ISSUE TITLE
R-package installation failure 

### ISSUE THREAD

**Issue by randxie** [aksnzhy/xlearn#59]
I tried to install the R package as instructed in makeR.sh but did not succeed. I am using Mac and my R version is 3.3.3. The error messages I got are:

Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '~/xlearn/xlearn.Rcheck/xlearn/libs/xlearn.so':
  dlopen(~/xlearn/xlearn.Rcheck/xlearn/libs/xlearn.so, 6): Symbol not found: __Z11XLearnFit_RP7SEXPRECS0_
  Referenced from: ~/xlearn/xlearn.Rcheck/xlearn/libs/xlearn.so
  Expected in: flat namespace
 in ~/xlearn/xlearn.Rcheck/xlearn/libs/xlearn.so
Error: loading failed
Execution halted
ERROR: loading failed

I tried to compile it with clang/gcc-4.9 and also linux platform but all failed. Any suggestions on how to fix this issue? Thanks a lot.

**Comment by aksnzhy** [comment]
Hi, the xLearn R package is still under developing in our inner version. We will release it as soon as possible.
