### ISSUE TITLE
ERROR: 'void xLearn::DMatrix::Compress(std::vector<unsigned int>&)':

### ISSUE THREAD

**Issue by wa1618i** [aksnzhy/xlearn#61]
I have tried using gcc version of 4.8,4.9,7 and 6...All failed to install xlearn?
Not sure why?

> lemma@lemma:~/xlearn$ mkdir build && cd build && cmake ..
> -- The C compiler identification is GNU 6.3.0
> -- The CXX compiler identification is GNU 5.4.1
> -- Check for working C compiler: /usr/bin/gcc
> -- Check for working C compiler: /usr/bin/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/g++
> -- Check for working CXX compiler: /usr/bin/g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: /home/lemma/anaconda2/bin/python (found version "2.7.14") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/lemma/xlearn/build
> lemma@lemma:~/xlearn/build$ make
> Scanning dependencies of target gtest
> [  1%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> [  2%] Linking CXX static library libgtest.a
> [  2%] Built target gtest
> Scanning dependencies of target gtest_main
> [  3%] Building CXX object gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
> [  4%] Linking CXX static library libgtest_main.a
> [  4%] Built target gtest_main
> Scanning dependencies of target base
> [  5%] Building CXX object src/base/CMakeFiles/base.dir/logging.cc.o
> [  6%] Building CXX object src/base/CMakeFiles/base.dir/stringprintf.cc.o
> [  7%] Building CXX object src/base/CMakeFiles/base.dir/split_string.cc.o
> [  8%] Building CXX object src/base/CMakeFiles/base.dir/levenshtein_distance.cc.o
> [  9%] Building CXX object src/base/CMakeFiles/base.dir/timer.cc.o
> [ 10%] Linking CXX static library libbase.a
> [ 10%] Built target base
> Scanning dependencies of target thread_pool_test
> [ 11%] Building CXX object src/base/CMakeFiles/thread_pool_test.dir/thread_pool_test.cc.o
> [ 12%] Linking CXX executable ../../test/base/thread_pool_test
> [ 12%] Built target thread_pool_test
> Scanning dependencies of target file_util_test
> [ 13%] Building CXX object src/base/CMakeFiles/file_util_test.dir/file_util_test.cc.o
> [ 14%] Linking CXX executable ../../test/base/file_util_test
> [ 14%] Built target file_util_test
> Scanning dependencies of target levenshtein_distance_test
> [ 15%] Building CXX object src/base/CMakeFiles/levenshtein_distance_test.dir/levenshtein_distance_test.cc.o
> [ 16%] Linking CXX executable ../../test/base/levenshtein_distance_test
> [ 16%] Built target levenshtein_distance_test
> Scanning dependencies of target data
> [ 17%] Building CXX object src/data/CMakeFiles/data.dir/model_parameters.cc.o
> In file included from /home/lemma/xlearn/src/data/model_parameters.h:31:0,
>                  from /home/lemma/xlearn/src/data/model_parameters.cc:23:
> /home/lemma/xlearn/src/data/data_structure.h: In member function 'void xLearn::DMatrix::Compress(std::vector<unsigned int>&)':
> /home/lemma/xlearn/src/data/data_structure.h:293:5: error: 'sort' is not a member of 'std'
>      std::sort(begin(feature_list), end(feature_list));
>      ^
> make[2]: *** [src/data/CMakeFiles/data.dir/model_parameters.cc.o] Error 1
> make[1]: *** [src/data/CMakeFiles/data.dir/all] Error 2
> make: *** [all] Error 2

**Comment by aksnzhy** [comment]
@wa1618i  Hi, I have updated the code, could you please try again?

**Comment by wa1618i** [comment]
Yes, it works THANKS
