### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by chenweilong915** [aksnzhy/xlearn#77]
Whatever I change python2 or 3, it raise the error.
The code is completely same as the examples, and I am sure that the libffm format data is correct(for I have test other libffm-pakages).

My cpu is Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz

**Comment by aksnzhy** [comment]
Could you please give me more error information?

**Comment by chenweilong915** [comment]
all it raise is the sentence:
"Illegal instruction (core dumped)"
So I don't know...
I use anaconda and pip install the xlearn, using python 2.7and python3.5,ubuntu

**Comment by aksnzhy** [comment]
You can check out the core dumped file for the error details.

**Comment by chenweilong915** [comment]
I find that it occured because of the pip...
I use the source code and everything works!
Thanks~
