### ISSUE TITLE
How to set early-stopping number in python param?

### ISSUE THREAD

**Issue by chenweilong915** [aksnzhy/xlearn#78]
I want to set early-stoping number to 10, but I  found there is no param for setting the early-stopping number.

**Comment by aksnzhy** [comment]
@chenweilong915 Hi, You can set the epoch number in both python and command line. What do you mean about 'early-stoping number'? Do you mean the early-stop window size?

**Comment by aksnzhy** [comment]
We added stop_window to the latest code.
