### ISSUE TITLE
xlearn api of sklearn xl.LRModel proformance is worse than sklearn's lr

### ISSUE THREAD

**Issue by hutaohutc** [aksnzhy/xlearn#81]
I use xlearn in my data,the same data for sklearn.lr and xl.LRModel ,sklearn.lr can get AUC 0.72,but xl.LRModel AUC only is 0.68 ,xl.FMModel's auc is also not very good and fmmodel's auc is only 0.67,and here is my code: 
```
linear_model = xl.LRModel(task='binary', init=0.1, 
                          epoch=20, lr=0.1, 
                          reg_lambda=1.0, opt='adagrad')

linear_model.fit(train_x_std, train_y, 
                 eval_set=[test_x_std, test_y])

y_pred = linear_model.predict(test_x_std)
roc_auc_score(test_y,y_pred)

fm_model = xl.FMModel(task='binary', init=0.66, 
                      epoch=10, k=4, lr=0.01,
                      reg_lambda=0.1, opt='adagrad', 
                      metric='auc')

fm_model.fit(train_x_std,train_y,eval_set=[test_x_std, test_y])
y_pred = fm_model.predict(test_x_std)
roc_auc_score(test_y,y_pred)

```
![image](https://user-images.githubusercontent.com/12443607/37387168-61cfc6d8-2796-11e8-98a6-45ca978e6078.png)

**Comment by aksnzhy** [comment]
The sklearn API doesn't take the same default hyper-parameters used by xlearn API. Please fine-tune your hyper-parameters to get the best score on your data.

**Comment by randxie** [comment]
@hutaohutc Without the data, my best guess is that the difference comes from different model parameter settings. For your reference, I created a simple example using iris data to compare logistic regression in xlearn and sklearn. The AUC score does not differ too much (xlearn is slightly higher).

# -------------------------------------------------------------------------
# Compare logistic regression in xlearn and sklearn
# -------------------------------------------------------------------------
import numpy as np
import xlearn as xl
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load dataset
iris_data = load_iris()
X = iris_data['data']
y = (iris_data['target'] == 2)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=0)

# LRModel in xlearn
linear_model = xl.LRModel(task='binary', init=0.1, 
                          epoch=10, lr=0.1, 
                          reg_lambda=1.0, opt='sgd')
linear_model.fit(X_train, y_train, is_lock_free=False)
y_pred_xl = linear_model.predict(X_val)
print("AUC for LRModel in xlearn is %f"%(roc_auc_score(y_val, y_pred_xl)))

# LogisticRegression in sklearn
mdl = LogisticRegression(C=1, penalty='l2')
mdl.fit(X_train, y_train)
y_pred_sk = mdl.predict(X_val)
print("AUC for LogisticRegression in sklearn is %f"%(roc_auc_score(y_val, y_pred_sk)))

**Comment by hutaohutc** [comment]
@randxie I can provide my data if you wanted。
When I use this parameter in my data ,my auc is less than 0.5.
```
linear_model = xl.LRModel(task='binary', init=0.1, 
                          epoch=20, lr=0.1, 
                          reg_lambda=1.0, opt='sgd')

linear_model.fit(train_x_std, train_y, 
                 eval_set=[test_x_std, test_y])
```
![image](https://user-images.githubusercontent.com/12443607/37445057-6979af2e-2850-11e8-9f45-2f920a0fc778.png)
 When I use another parameter ,I only change opt to ada grad ,the auc performance improved,but is also bou so good.
```
linear_model = xl.LRModel(task='binary', init=0.1, 
                          epoch=20, lr=0.1, 
                          reg_lambda=1.0, opt='adgrad')

linear_model.fit(train_x_std, train_y, 
                 eval_set=[test_x_std, test_y])
```
![image](https://user-images.githubusercontent.com/12443607/37445168-31e1eb3e-2851-11e8-9a05-9582661bd9dc.png)


These two sets of parameters is also worse than skleran's lr .  sklearn's performance is as follows.

![image](https://user-images.githubusercontent.com/12443607/37445294-2deaa79a-2852-11e8-9d6b-04b2e5b8c63b.png)


 
Can you provide some trick of turn paramater in xlearn? Thank you for your time ~

**Comment by 77QingLiu** [comment]
same issue in xlearn.
Sklearn's cross-validation score is 0.99 and it's stable, but in Xlearn is 0.85 and not stable.
Quiet weird
