### ISSUE TITLE
support of csv format

### ISSUE THREAD

**Issue by yitang** [aksnzhy/xlearn#9]
the documentation says xlearn supports csv format but i got this error:
 
![screenshot from 2017-11-26 11-25-47](https://user-images.githubusercontent.com/6054101/33239578-9893a1e8-d29c-11e7-97c3-b32a87691241.png)

**Comment by aksnzhy** [comment]
Hi，can you share a portion of your data on this issue? We will check it right now.

**Comment by yitang** [comment]
0,2,2,5,1,0,0,1,0,0,0,0,0,0,0,11,0,1,0,0.7,0.2,10,1,-1,0,1,4,1,0,0,1,12,2,0.5,0.2,3,1,10,1,10,1,5,9,1,5,8,0,1,1,0,0,1
0,1,1,7,0,0,0,0,1,0,0,0,0,0,0,3,0,0,1,0.8,0.4,11,1,-1,0,-1,11,1,1,2,1,19,3,0.1,0.3,2,1,9,5,8,1,7,3,1,1,9,0,1,1,0,1,0
0,5,4,9,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.0,0.0,7,1,-1,0,-1,14,1,1,2,1,60,1,0.7,0.1,2,2,9,1,8,2,7,4,2,7,7,0,1,1,0,1,0
0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,8,1,0,0,0.9,0.2,7,1,0,0,1,11,1,1,3,1,104,1,0.9,0.1,2,4,7,1,8,4,2,2,2,4,9,0,0,0,0,0,0
0,0,2,0,1,0,1,0,0,0,0,0,0,0,0,9,1,0,0,0.7,0.6,11,1,-1,0,-1,14,1,1,2,1,82,3,0.6,0.0,2,2,6,3,10,2,12,3,1,1,3,0,0,0,1,1,0
0,5,1,4,0,0,0,0,0,1,0,0,0,0,0,6,1,0,0,0.9,1.8,10,0,-1,0,0,14,1,1,0,1,104,2,0.8,0.4,3,1,8,2,11,3,8,4,2,0,9,0,1,0,1,1,1
0,2,1,3,1,0,0,1,0,0,0,0,0,0,0,8,1,0,0,0.6,0.1,6,1,-1,0,1,11,1,1,0,1,99,2,0.6,0.5,2,2,8,1,8,3,10,3,0,0,10,0,1,0,0,1,0
0,5,1,4,0,0,1,0,0,0,0,0,0,0,0,13,1,0,0,0.7,0.4,11,1,0,0,0,11,1,1,2,1,30,3,0.5,0.1,1,2,7,1,6,1,13,7,1,3,6,1,0,1,0,1,0
0,5,1,3,1,0,0,0,1,0,0,0,0,0,0,6,1,0,0,0.9,0.7,10,1,-1,0,1,14,1,1,0,1,68,3,0.8,0.6,3,1,7,3,9,4,11,4,2,1,5,0,1,0,0,0,1
1,1,1,2,0,0,0,1,0,0,0,0,0,0,0,4,0,0,1,0.9,1.4,11,0,0,1,0,14,1,1,2,1,104,2,0.8,0.8,2,2,8,2,9,1,11,3,5,0,6,0,1,0,0,1,0
0,5,2,2,0,0,0,0,1,0,0,0,0,0,0,3,1,0,0,0.5,0.4,11,1,-1,8,-1,13,1,1,2,1,20,3,0.1,0.0,2,3,8,2,9,4,7,6,3,3,6,0,1,1,0,1,1
0,2,1,3,1,0,0,1,0,0,0,0,0,0,0,9,1,0,0,0.9,0.1,11,0,-1,0,-1,11,1,0,0,1,36,3,0.7,0.5,2,2,8,2,10,1,8,9,2,1,10,0,1,0,1,0,0
0,2,1,1,1,0,0,0,1,0,0,0,0,0,0,10,1,0,0,0.5,0.2,6,1,-1,0,-1,11,1,1,2,1,101,3,0.8,0.9,4,1,8,4,11,1,9,6,3,3,8,0,0,1,0,0,1
0,1,1,3,1,0,0,1,0,0,0,0,0,0,0,12,1,0,0,0.7,0.9,9,1,0,0,1,6,1,1,2,1,104,3,0.7,0.6,2,1,10,1,8,3,8,2,0,4,3,0,0,1,0,1,0
0,5,1,11,0,0,0,0,0,1,0,0,0,0,0,10,0,0,1,0.8,0.6,11,1,-1,0,-1,11,1,1,2,1,103,1,0.4,0.1,3,1,8,2,6,3,12,4,1,3,9,0,0,0,0,1,0
0,5,1,3,1,0,0,1,0,0,0,0,0,0,0,5,0,0,1,0.4,0.3,6,1,-1,9,1,15,1,0,0,1,41,2,0.4,0.2,2,1,9,5,10,2,13,5,2,6,7,0,1,1,0,1,0
0,1,2,1,0,0,0,0,1,0,0,0,0,0,0,9,1,0,0,0.6,0.3,11,1,-1,1,-1,3,1,1,0,1,59,3,0.0,0.3,2,1,10,6,7,3,5,3,3,1,8,0,0,1,0,0,0
0,5,1,6,0,1,1,0,0,0,0,0,0,0,0,4,1,0,0,0.9,0.5,11,1,1,0,0,11,1,0,2,1,104,2,0.6,0.1,1,3,8,2,9,1,10,9,1,3,9,0,1,1,0,0,0
0,5,1,8,0,0,1,0,0,0,0,0,0,0,0,12,1,0,0,0.3,0.3,7,1,-1,0,-1,0,1,1,2,1,43,3,0.3,0.3,3,1,8,3,11,2,11,3,1,6,5,0,0,0,1,0,0

**Comment by yitang** [comment]
please see above for the csv files. the first column is the target. is it what xlearn expecting?

**Comment by aksnzhy** [comment]
I know，for now you can change the , to space or \t，we will add the , to our data format

**Comment by yitang** [comment]
'space' works fine. xlearn is able to read it. but the results are bad.  auc is about 0.5~0.6. i also noticed a strange thing:

[------------] Number of Feature: 45
[------------] Number of Field: 1


There's only one field...

**Comment by aksnzhy** [comment]
You need to use the libfffm format for the ffm task ，csv can only used in linear model and fm.

**Comment by aksnzhy** [comment]
CSV is not a good format for ffm because ffm are usually be used in sparse data.

**Comment by yitang** [comment]
I see. That make senses. Thanks. 

I tried once running GLM (s=0 option) and it ran through. Should xlearn do some input validation?

**Comment by aksnzhy** [comment]
We will improve our checker these days. Thanks for your issue!

**Comment by yitang** [comment]
okay thanks
