### ISSUE TITLE
How to get the feature representation after decomposition

### ISSUE THREAD

**Issue by liangjie18430** [aksnzhy/xlearn#90]
Can I get a feature vector representation of the Cross features in FM, no related APIs is found

**Comment by aksnzhy** [comment]
@liangjie18430 Please see set setTXTModel() API in python and -t option in command line.

**Comment by randxie** [comment]
@aksnzhy Do you think it is worth adding the weight vector/matrix as properties of FMModel, LRModel and FFMModel. We could call setTXTModel() inside the sklearn interface and parse the txt afterwards.

**Comment by aksnzhy** [comment]
@randxie I think it’s good to add this feature to sklearn API .
