### ISSUE TITLE
Change nthread parmeter name in sklearn wrapper  to n_jobs

### ISSUE THREAD

**Issue by mpearmain** [aksnzhy/xlearn#91]
The current Sklearn API for Xlearn does not follow Sklearn conventions -  "nthread" should be "n_jobs"

Similar to XGBoost 
https://github.com/dmlc/xgboost/pull/2658/files

**Comment by aksnzhy** [comment]
Thanks for this! We will update it.

**Comment by aksnzhy** [comment]
@randxie Could you please change the 'nthread' argument to 'n_jobs', but remain the 'nthread' argument in the original python API?
