### ISSUE TITLE
Bug related to Quiet Training

### ISSUE THREAD

**Issue by lzb5600** [aksnzhy/xlearn#95]
It seems that **early stop** doesn't work when using setQuiet()

**Comment by aksnzhy** [comment]
We will check this bug. Thank you!

**Comment by aksnzhy** [comment]
Hi, I found that this is not a bug but a feature. When using quite training, the system will not do any evaluation to speed up training, and hence the early-stop will not be performed.

**Comment by lzb5600** [comment]
Thanks for the explanation!
