### ISSUE TITLE
Questions related to model initialization and parameters of AdaGrad

### ISSUE THREAD

**Issue by lzb5600** [aksnzhy/xlearn#98]
Does command line option -u correspond to -init stdev in LibFM which sets the standard deviation for initializing the parameters V? And how do you set the initial value for accumulated gradient G? I cannot find it in xlearn documents. Could you give some comments? Thanks.

**Comment by aksnzhy** [comment]
-u is a threshold, and we will initialize our linear term to 0.0 and latent factor to (0.0 ~ threshold).

All the accumulated gradient in Adagrad will be initialized to 1.0

**Comment by lzb5600** [comment]
Thanks for your comments. As you description, -u is the parameter for uniform distribution [0, Threshold].

**Comment by aksnzhy** [comment]
Strictly, it is (0, Threshold]. We cannot set the parameter of latent factor to zero. Because in that case, the gradient will always be zero.

**Comment by lzb5600** [comment]
Yes, you are right. Thanks!
